# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
    - nodejs_version: '8'

  DEBUG: phenomic:*

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - curl -fsSL -o yarn.js https://nightly.yarnpkg.com/yarn-1.0.0-20170820.2056.js
  - node ./yarn.js --version
  - node ./yarn.js install

test_script:
  - node ./yarn.js run test

cache:
  - node_modules -> package.json
  - docs/.screenshots -> docs/content/showcase-entries
  - docs/public/showcase/entry -> docs/content/showcase-entries

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

init:
  # debugging Appveyor build. More info:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
